#!/bin/bash
. $WM_PROJECT_DIR/bin/tools/RunFunctions

name="$1"

# Clean the case
./Allclean

# generate the mesh
echo "running blockMesh"
blockMesh > log.blockMesh
echo "running decomposePar"
decomposePar > /dev/null
echo "running Snappy"
mpirun -np 3 snappyHexMesh -parallel &> log.snappyHexMesh
echo "running reconstructParMesh"
reconstructParMesh -latestTime > /dev/null
echo "running reconstructPar"
reconstructPar -latestTime > /dev/null

# save the mesh images
printf "Generating mesh images...\n"
~/temp/ParaView-5.9.1-MPI-Linux-Python3.8-64bit/bin/pvpython pvscript.py $name
